# Dovecot configuration file

# Enable installed protocols
!include_try /usr/share/dovecot/protocols.d/*.protocol

# Protocols to enable
protocols = imap lmtp

# Include configuration files
!include conf.d/*.conf

# Try to include local configuration
!include_try local.conf
